### ISSUE TITLE
Graph neighbours

### ISSUE THREAD

**Issue by brechtvdv** [brechtvdv/gtfs2connections#3]
While generating connections, keep track of Minimum Spanning Tree for every stop to its directly reachable stops. (= reachable in one trip)

Also keep track of the minimum time it takes.

**Comment by pietercolpaert** [comment]
Why would this be useful in particular?

**Comment by brechtvdv** [comment]
The server uses this information to build a minimum spanning tree of K closest stops of a departure stop. When it queries the neighbours, it can use the minimum time for the departure time parameter. Does this make sense to you?

**Comment by pietercolpaert** [comment]
It's an interesting idea! Didn't think of it that way yet! Do proceed :)

**Comment by pietercolpaert** [comment]
Remark: this is not an MST: it may be shorter in time to take 3 hops instead of just 1 hop which is in your data.

Call it graph neighbours

**Comment by pietercolpaert** [comment]
Or X-level neighbourhood

**Comment by brechtvdv** [comment]
Thanks for the remark!
