### ISSUE TITLE
Add coordinates of stops to connections

### ISSUE THREAD

**Issue by brechtvdv** [brechtvdv/gtfs2connections#4]
As the lc-client doesn't have a stops/footpaths system, I'll add the coordinates of the arrival and departure stop to every connection. This way the client knows the location of the stops and can choose a next departure stop for the optimization heuristic.

**Comment by brechtvdv** [comment]
I believe it's easier and more data efficient to hold the stops in a levelDB at clientside

**Comment by pietercolpaert** [comment]
+1 for keeping this on client-side for now!
